CREATE TABLE ESCOLA (
    ID_ESCOLA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE IP (
    ID_IP INT PRIMARY KEY,
    ID_ESCOLA INT NOT NULL,
    ENDERECO_IP VARCHAR(45) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID_ESCOLA)
);

CREATE TABLE PACOTE (
    ID_PACOTE INT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    LIMITE_ACESSOS_MENSAIS INT NOT NULL,
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE ASSINATURA (
    ID_ASSINATURA INT PRIMARY KEY,
    ID_ESCOLA INT NOT NULL,
    ID_PACOTE INT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    STATUS VARCHAR(20) NOT NULL, 
    FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID_ESCOLA),
    FOREIGN KEY (ID_PACOTE) REFERENCES PACOTE(ID_PACOTE)
);

CREATE TABLE GAME (
    ID_GAME INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE ACESSO (
    ID_ACESSO INT PRIMARY KEY,
    ID_ESCOLA INT NOT NULL,
    ID_GAME INT NOT NULL,
    ID_ASSINATURA INT NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    IP_ORIGEM VARCHAR(45) NOT NULL,
    CONTABILIZACAO BOOLEAN NOT NULL, 
    FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID_ESCOLA),
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME),
    FOREIGN KEY (ID_ASSINATURA) REFERENCES ASSINATURA(ID_ASSINATURA)
);

CREATE TABLE RELATORIO (
    ID_RELATORIO INT PRIMARY KEY,
    ID_ESCOLA INT NOT NULL,
    ID_ASSINATURA INT NOT NULL,
    MES_REFERENCIA DATE NOT NULL,
    TOTAL_ACESSOS INT NOT NULL,
    FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID_ESCOLA),
    FOREIGN KEY (ID_ASSINATURA) REFERENCES ASSINATURA(ID_ASSINATURA)
);

CREATE TABLE IP_ATIVO (
    ID_IP_ATIVO INT PRIMARY KEY,
    ID_PACOTE INT NOT NULL,
    ENDERECO_IP VARCHAR(45) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    FOREIGN KEY (ID_PACOTE) REFERENCES PACOTE(ID_PACOTE)
);
